import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { DiscordSignIn } from "@/app/components/DiscordSignIn";
import { DiscordAvatar } from "@/app/components/DiscordAvatar";
import { auth } from "@/auth";
import { SignOut } from "@/app/components/signout";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
    console.log("Session:", session);
  
    const sign = session?.user ? <SignOut /> : <DiscordSignIn />;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <div className="flex flex-col gap-4 text-base font-medium sm:flex-row">
            <a> <DiscordAvatar /> </a>
            <a> {sign} </a>            
          </div>
        {children}
      </body>
    </html>
  );
}
